# Site settings
title: basicseed.boilerplate
email: james@jamesdmosier.com
description: basicseed.boilerplate is a starting point for new projects, another framework
baseurl: "/basicseedboilerplate/" # the subpath of your site, e.g. /blog/
url: "http://jamez14.github.io" # the base hostname & protocol for your site
twitter_username: jamez14
github_username:  jamez14

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge

# Server
#source:			docs
encoding:		UTF-8
#destination: 	/
